package Player;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;

/**
 * Created by omi on 4/24/16.
 */
@SuppressWarnings("serial")
public class AVPlayer extends javax.swing.JFrame {

    private String FRAMES_FILE;
    private String AUDIO_FILE;

    private int WIDTH = 480;
    private int HEIGHT = 270;

    private boolean isPlaying;
    private long seekPositionVideo;
    private long seekPositionAudio;

    private AudioPlayer audioPlayer;
    private InputStream frameStream;

    /**
     * Creates new form PlayerFrame
     */
    public AVPlayer(String RGB_FILE, String AUDIO_FILE) {
        initComponents();
        try {
            loadResources(RGB_FILE, AUDIO_FILE);

            setLocationRelativeTo(null);
            setVisible(true);

            play();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /*
       Utility functions to control the video Component
     */
    private void loadResources(String RGB_FILE, String AUDIO_FILE) throws Exception {
        this.FRAMES_FILE = RGB_FILE;
        this.AUDIO_FILE = AUDIO_FILE;

        audioPlayer = new AudioPlayer(new FileInputStream(this.AUDIO_FILE));
        frameStream = new FileInputStream(new File(this.FRAMES_FILE));

    }

    private BufferedImage getNextFrame() throws Exception {
        BufferedImage img = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_RGB);
        long len = WIDTH * HEIGHT * 3;
        byte[] bytes = new byte[(int) len];

        int offset = 0;
        int numRead;
        while (offset < bytes.length && (numRead = frameStream.read(bytes, offset, bytes.length - offset)) >= 0) {
            offset += numRead;
        }

        //Generate Buffered Image
        int ind = 0;
        for (int y = 0; y < HEIGHT; y++) {

            for (int x = 0; x < WIDTH; x++) {

                byte a = 0;
                byte r = bytes[ind];
                byte g = bytes[ind + HEIGHT * WIDTH];
                byte b = bytes[ind + HEIGHT * WIDTH * 2];

                int pix = 0xff000000 | ((r & 0xff) << 16) | ((g & 0xff) << 8) | (b & 0xff);
                img.setRGB(x, y, pix);
                ind++;
            }
        }
        return img;
    }

    /*AV controls  to Play, Pause, and stop the video */
    private void play() throws Exception{
        audioPlayer.play();
        Thread videoThread = new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                    try{
                        frameContainer.setIcon(new ImageIcon(getNextFrame()));
                        Thread.sleep(67);
                    }catch(Exception ex){
                        ex.printStackTrace();
                    }
                }
            }
        });
        videoThread.start();
    }

    private void pause() {

    }

    private void stop() {

    }

    //USELESS
    public void setFrame(BufferedImage img){
        this.frameContainer.setIcon(new ImageIcon(img));
    }
    public void setColor(Color color){
        this.controlContainer.setBackground(color);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        videoContainer = new javax.swing.JPanel();
        frameContainer = new javax.swing.JLabel();
        controlContainer = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        seekBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Player");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        videoContainer.setBackground(new java.awt.Color(255, 255, 255));
        videoContainer.setPreferredSize(new java.awt.Dimension(480, 270));

        frameContainer.setBackground(new java.awt.Color(255, 255, 255));
        frameContainer.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        frameContainer.setBorder(null);
        frameContainer.setFocusable(false);
        frameContainer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        frameContainer.setIconTextGap(0);

        javax.swing.GroupLayout videoContainerLayout = new javax.swing.GroupLayout(videoContainer);
        videoContainer.setLayout(videoContainerLayout);
        videoContainerLayout.setHorizontalGroup(
                videoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(frameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        videoContainerLayout.setVerticalGroup(
                videoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(frameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        controlContainer.setBackground(new java.awt.Color(50, 50, 50));
        controlContainer.setMaximumSize(new java.awt.Dimension(480, 50));
        controlContainer.setMinimumSize(new java.awt.Dimension(480, 50));

        playButton.setText("PLAY");
        playButton.setPreferredSize(new java.awt.Dimension(80, 30));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        stopButton.setText("STOP");
        stopButton.setPreferredSize(new java.awt.Dimension(80, 30));
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlContainerLayout = new javax.swing.GroupLayout(controlContainer);
        controlContainer.setLayout(controlContainerLayout);
        controlContainerLayout.setHorizontalGroup(
                controlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(controlContainerLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(143, Short.MAX_VALUE))
        );
        controlContainerLayout.setVerticalGroup(
                controlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(controlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        seekBar.setBackground(new java.awt.Color(255, 255, 255));
        seekBar.setBorder(null);
        seekBar.setPreferredSize(new java.awt.Dimension(480, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(controlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seekBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(videoContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(videoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(seekBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(controlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JPanel controlContainer;
    private javax.swing.JLabel frameContainer;
    private javax.swing.JButton playButton;
    private javax.swing.JProgressBar seekBar;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel videoContainer;
    // End of variables declaration
}

